name: geoflutterfire_example
description: Demonstrates how to use the geoflutterfire plugin.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  geoflutterfire:
    path: ../

  cloud_firestore: ^4.8.2
  google_maps_flutter: ^2.1.1

flutter:
  uses-material-design: true
